apiVersion: v1
kind: Service
metadata: 
   name: fleetman-webapps
spec:
   # this defines which pods are going to be represented by this Service
   #The service becomes a network endpoint for either other services
   # or maybe external users to connect to (eg Browser)
   selector:
      app: webapp

   ports:
      - name: http
        port: 80
        nodePort: 30080

   type: NodePort 

---

apiVersion: v1
kind: Service
metadata: 
   name: queue
spec:
   # this defines which pods are going to be represented by this Service
   #The service becomes a network endpoint for either other services
   # or maybe external users to connect to (eg Browser)
   selector:
      app: queue
      release: "1"

   ports:
      - name: http
        port: 8161
        nodePort: 30010

   type: NodePort 
